#!/bin/bash
echo "Hello, Emmanuel"
sleep 2
echo "================================================"
echo "Checking current git status..."
echo "================================================"
git status
sleep 5

echo "================================================"
echo "Staging files in the current directory..."
echo "================================================"
git add .
sleep 3

echo "================================================"
echo "Staging Done..."
echo "================================================"
echo "Checking current git status again..."
echo "================================================"
git status
sleep 3

echo "================================================"
echo "Enter your commit message here:"
read MESSAGE
echo "================================================"
echo "Commit message added successfully!"
git commit -m "$MESSAGE"
sleep 3

echo "================================================"
echo "Preparing to push..."
echo "================================================"
sleep 2

echo "================================================"
echo "Pushing...."
echo "================================================"
git push
sleep 1

echo "================================================"
echo "Done Boss!!!"
echo "================================================"
